import { Inter, Open_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const opensans = Open_Sans({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>{children}</body>
    </html>
  );
}
